// lib/default-content.ts
import type { FullContent } from "./content-types"

export const defaultContent: FullContent = {
  hero: {
    imageUrl: "https://az316141.cdn.laget.se/2317159/11348130.jpg",
    title: "LAGET FÖRE ALLT",
    description: "Härnösands HF - En förening med stolthet, gemenskap och passion för sporten.",
    button1Text: "Våra 23 Lag",
    button1Link: "/lag",
    button2Text: "Senaste Nytt",
    button2Link: "/nyheter",
  },
  stats: {
    totalTeams: 23,
    aTeams: 2,
    youthTeams: 21,
    yearsHistory: "50+",
  },
  aboutClub: {
    title: "Härnösands HF",
    paragraph1:
      "Vi är en handbollsklubb som värnar om gemenskap, utveckling och sund konkurrens. Med våra 23 lag från ungdom till seniorer erbjuder vi handboll för alla åldrar och nivåer.",
    paragraph2:
      "Vår vision är att vara den ledande handbollsklubben i regionen genom att skapa en miljö där varje spelare kan utvecklas och trivas.",
    passionText: "Vi brinner för handboll",
    developmentText: "Alla kan bli bättre",
    communityText: "Tillsammans är vi starka",
    button1Text: "Visa Lag",
    button1Link: "/lag",
    button2Text: "Kontakta Oss",
    button2Link: "/kontakt",
    imageSrc: "https://i.ibb.co/Zt8gppK/491897759-17872413642339702-3719173158843008539-n.jpg",
    imageAlt: "Härnösands HF Team",
    statNumber: 23,
    statLabel: "lag totalt",
  },
  partners: [
    {
      id: "highcon",
      src: "https://highcon.se/media/w5zbh52t/logotype.svg",
      alt: "Highcon",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://www.highcon.se",
    },
    {
      id: "hsta",
      src: "https://az729104.cdn.laget.se/11313578.jpg",
      alt: "HSTA",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://www.hsta.se",
    },
    {
      id: "harnosands-platslageri",
      src: "https://az729104.cdn.laget.se/11311616.png",
      alt: "Härnösands Plåtslageri",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://www.harnosandsplatslageri.se",
    },
    {
      id: "jasab",
      src: "https://az729104.cdn.laget.se/11313577.jpg",
      alt: "Jasab",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://www.jasab.se",
    },
    {
      id: "jj-bygg",
      src: "https://az729104.cdn.laget.se/11314727.jpg",
      alt: "JJ Bygg",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://jjbyggab.com",
    },
    {
      id: "ohmy",
      src: "https://az729104.cdn.laget.se/11313553.jpg",
      alt: "Ohmy",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://ohmy.se",
    },
    {
      id: "westerlinds",
      src: "https://westerlinds.nu/wp-content/themes/westerlinds20/img/logo-new-full.svg",
      alt: "Westerlinds",
      width: 150,
      height: 75,
      tier: "Diamantpartner",
      benefits: ["Huvudsponsor", "Logotyp på matchställ", "Exklusiva event"],
      visibleInCarousel: true,
      linkUrl: "https://westerlinds.nu",
    },
    {
      id: "forsakringskonsult",
      src: "https://az729104.cdn.laget.se/11308402.jpg",
      alt: "Försäkringskonsult",
      width: 150,
      height: 75,
      tier: "Platinapartner",
      benefits: ["Logotyp på hemsida", "Synlighet vid hemmamatcher"],
      visibleInCarousel: true,
      linkUrl: "https://forsakringskonsult.com",
    },
    {
      id: "bargab",
      src: "https://az729104.cdn.laget.se/11314769.png",
      alt: "Bärgab",
      width: 150,
      height: 75,
      tier: "Guldpartner",
      benefits: ["Logotyp på hemsida", "Synlighet vid hemmamatcher"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "mekonomen",
      src: "https://d3sjey3kqst1or.cloudfront.net/static/version1750738442/frontend/Mekonomen/Mek/sv_SE/images/main-logo.svg",
      alt: "Mekonomen",
      width: 150,
      height: 75,
      tier: "Guldpartner",
      benefits: ["Logotyp på hemsida", "Synlighet vid hemmamatcher"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "sca",
      src: "https://az729104.cdn.laget.se/11314773.png",
      alt: "SCA",
      width: 150,
      height: 75,
      tier: "Guldpartner",
      benefits: ["Logotyp på hemsida", "Synlighet vid hemmamatcher"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "coop",
      src: "https://az729104.cdn.laget.se/11314752.jfif",
      alt: "Coop",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: false,
      linkUrl: undefined,
    },
    {
      id: "ekebro-utveckling",
      src: "https://files.builder.misssite.com/f6/e9/f6e9e4a2-6fbb-4f4c-9fb6-04e1845c8b52.png",
      alt: "Ekebro Utveckling",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "harnosandshus",
      src: "https://az729104.cdn.laget.se/11314757.png",
      alt: "Härnösandshus",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "j-sjolunds-varme",
      src: "https://az729104.cdn.laget.se/11314761.png",
      alt: "J Sjölunds Värme",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "norrskydd",
      src: "https://az729104.cdn.laget.se/11314763.jfif",
      alt: "Norrskydd",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
    {
      id: "lansforsakringar",
      src: "https://az729104.cdn.laget.se/11314767.png",
      alt: "Länsförsäkringar",
      width: 150,
      height: 75,
      tier: "Silverpartner",
      benefits: ["Logotyp på hemsida"],
      visibleInCarousel: true,
      linkUrl: undefined,
    },
  ],
  sections: ["hero", "stats", "upcomingEvents", "aboutClub", "partnersCarousel"],
}
