export interface Partner {
  id: string
  name: string
  src: string
  alt: string
  tier: "Diamantpartner" | "Platinapartner" | "Guldpartner" | "Silverpartner" | "Bronspartner"
  linkUrl?: string
  visibleInCarousel: boolean
}

export const allPartners: Partner[] = [
  {
    id: "harnosand-kommun",
    name: "Härnösands Kommun",
    src: "/placeholder-logo.svg?height=80&width=120&query=Härnösands Kommun logo",
    alt: "Härnösands Kommun",
    tier: "Diamantpartner",
    linkUrl: "https://harnosand.se",
    visibleInCarousel: true,
  },
  {
    id: "sparbanken-nord",
    name: "Sparbanken Nord",
    src: "/placeholder-logo.svg?height=80&width=120&query=Sparbanken Nord logo",
    alt: "Sparbanken Nord",
    tier: "Diamantpartner",
    linkUrl: "https://www.sparbankennord.se",
    visibleInCarousel: true,
  },
  {
    id: "ica-maxi",
    name: "ICA Maxi Härnösand",
    src: "/placeholder-logo.svg?height=80&width=120&query=ICA Maxi logo",
    alt: "ICA Maxi Härnösand",
    tier: "Platinapartner",
    linkUrl: "https://www.ica.se/butiker/maxi/harnosand/ica-maxi-harnosand-12345/",
    visibleInCarousel: true,
  },
  {
    id: "coop",
    name: "Coop Härnösand",
    src: "/placeholder-logo.svg?height=80&width=120&query=Coop logo",
    alt: "Coop Härnösand",
    tier: "Platinapartner",
    linkUrl: "https://www.coop.se/butiker/coop-harnosand/",
    visibleInCarousel: true,
  },
  {
    id: "byggmax",
    name: "Byggmax",
    src: "/placeholder-logo.svg?height=80&width=120&query=Byggmax logo",
    alt: "Byggmax",
    tier: "Guldpartner",
    linkUrl: "https://www.byggmax.se",
    visibleInCarousel: true,
  },
  {
    id: "elon",
    name: "Elon",
    src: "/placeholder-logo.svg?height=80&width=120&query=Elon logo",
    alt: "Elon",
    tier: "Guldpartner",
    linkUrl: "https://www.elon.se",
    visibleInCarousel: true,
  },
  {
    id: "bilbolaget",
    name: "Bilbolaget",
    src: "/placeholder-logo.svg?height=80&width=120&query=Bilbolaget logo",
    alt: "Bilbolaget",
    tier: "Silverpartner",
    linkUrl: "https://www.bilbolaget.com",
    visibleInCarousel: true,
  },
  {
    id: "harnosand-energi",
    name: "Härnösand Energi",
    src: "/placeholder-logo.svg?height=80&width=120&query=Härnösand Energi logo",
    alt: "Härnösand Energi",
    tier: "Silverpartner",
    linkUrl: "https://www.harnosandenergi.se",
    visibleInCarousel: true,
  },
  {
    id: "restaurang-strand",
    name: "Restaurang Strand",
    src: "/placeholder-logo.svg?height=80&width=120&query=Restaurang Strand logo",
    alt: "Restaurang Strand",
    tier: "Bronspartner",
    linkUrl: "https://www.restaurangstrand.se",
    visibleInCarousel: true,
  },
  {
    id: "sportringen",
    name: "Sportringen",
    src: "/placeholder-logo.svg?height=80&width=120&query=Sportringen logo",
    alt: "Sportringen",
    tier: "Bronspartner",
    linkUrl: "https://www.sportringen.se",
    visibleInCarousel: true,
  },
  {
    id: "highcon",
    name: "Highcon",
    src: "/placeholder-logo.svg?height=80&width=120&query=Highcon logo",
    alt: "Highcon",
    tier: "Diamantpartner",
    linkUrl: "https://www.highcon.com",
    visibleInCarousel: true,
  },
  {
    id: "nordea",
    name: "Nordea",
    src: "/placeholder-logo.svg?height=80&width=120&query=Nordea logo",
    alt: "Nordea",
    tier: "Platinapartner",
    linkUrl: "https://www.nordea.se",
    visibleInCarousel: true,
  },
  {
    id: "swedbank",
    name: "Swedbank",
    src: "/placeholder-logo.svg?height=80&width=120&query=Swedbank logo",
    alt: "Swedbank",
    tier: "Guldpartner",
    linkUrl: "https://www.swedbank.se",
    visibleInCarousel: true,
  },
  {
    id: "seb",
    name: "SEB",
    src: "/placeholder-logo.svg?height=80&width=120&query=SEB logo",
    alt: "SEB",
    tier: "Silverpartner",
    linkUrl: "https://www.seb.se",
    visibleInCarousel: true,
  },
  {
    id: "handelsbanken",
    name: "Handelsbanken",
    src: "/placeholder-logo.svg?height=80&width=120&query=Handelsbanken logo",
    alt: "Handelsbanken",
    tier: "Bronspartner",
    linkUrl: "https://www.handelsbanken.se",
    visibleInCarousel: true,
  },
]
