import type { Partner } from "./content-types"

export const allPartners: Partner[] = [
  {
    id: "harnosand-kommun",
    alt: "Härnösands Kommun",
    src: "/placeholder-logo.svg",
    tier: "Diamantpartner",
    linkUrl: "https://harnosand.se",
    benefits: ["Stödjer ungdomsidrott", "Långsiktigt samarbete"],
    visibleInCarousel: true,
  },
  {
    id: "sparbanken-nord",
    alt: "Sparbanken Nord",
    src: "/placeholder-logo.svg",
    tier: "Platinapartner",
    linkUrl: "https://sparbankennord.se",
    benefits: ["Lokal förankring", "Ekonomiskt stöd"],
    visibleInCarousel: true,
  },
  {
    id: "ica-maxi",
    alt: "ICA Maxi",
    src: "/placeholder-logo.svg",
    tier: "Guldpartner",
    linkUrl: "https://maxi.ica.se/harnosand",
    benefits: ["Mat till evenemang", "Sponsor av cuper"],
    visibleInCarousel: true,
  },
  {
    id: "sportringen",
    alt: "Sportringen",
    src: "/placeholder-logo.svg",
    tier: "Silverpartner",
    linkUrl: "https://sportringen.se",
    benefits: ["Utrustning", "Klubbkläder"],
    visibleInCarousel: true,
  },
  {
    id: "harnosands-energi",
    alt: "Härnösands Energi",
    src: "/placeholder-logo.svg",
    tier: "Bronspartner",
    linkUrl: "https://harnosandsenergi.se",
    benefits: ["Hållbarhet", "Lokalt engagemang"],
    visibleInCarousel: true,
  },
  {
    id: "highcon",
    alt: "Highcon",
    src: "/placeholder-logo.svg",
    tier: "Diamantpartner",
    linkUrl: "https://highcon.se",
    benefits: ["Teknikpartner", "Digital utveckling"],
    visibleInCarousel: true,
  },
  {
    id: "restaurang-strand",
    alt: "Restaurang Strand",
    src: "/placeholder-logo.svg",
    tier: "Guldpartner",
    linkUrl: "https://restaurangstrand.se",
    benefits: ["Lagmiddagar", "Event catering"],
    visibleInCarousel: true,
  },
  {
    id: "bilbolaget",
    alt: "Bilbolaget",
    src: "/placeholder-logo.svg",
    tier: "Silverpartner",
    linkUrl: "https://bilbolaget.com",
    benefits: ["Transportlösningar", "Fordonsstöd"],
    visibleInCarousel: true,
  },
  {
    id: "byggmax",
    alt: "Byggmax",
    src: "/placeholder-logo.svg",
    tier: "Bronspartner",
    linkUrl: "https://byggmax.se",
    benefits: ["Material till anläggningar"],
    visibleInCarousel: true,
  },
  {
    id: "coop-harnosand",
    alt: "Coop Härnösand",
    src: "/placeholder-logo.svg",
    tier: "Guldpartner",
    linkUrl: "https://coop.se/butiker/coop-harnosand",
    benefits: ["Livsmedelssponsor"],
    visibleInCarousel: true,
  },
]
